title: 멜로디-Melody
description: 멜로디-Melody- Menampilkan Music Up to date

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: ApplicationD
   twitter: @Nicha_lachh
   facebook: Nika Wati
   email: Nikawati39@gmail.com

google_analytics: "UA-58263416-1"
