title: 멜로디-Melody
description: 멜로디-Melody Menampilkan Lantunan music yang klasik dan kuno

url: http://ApplicationD.github.io/멜로디-Melody
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: Nikawati
   twitter: nicha_lachh
   facebook: Nika Wati [https://www.facebook.com/nicka.cyngortu]
   email: Nikawati39@gmail.com

google_analytics: "UA-58263416-1"
